spring:
  main:
    log-startup-info: true
  application:
    name: sample-webapp-servlet

server:
  address: localhost
  port: 9100
  servlet:
    context-path: /samples/webapp-servlet/api
    
logging:
  level:
    mike.bootstrap: DEBUG
    mike.bootstrap.samples: DEBUG
    web: INFO
